// DO NOT EDIT. This file is generated by Fastfile.
enum FunctionName: String {
    case bezierInterpolation = "bezier_interpolation"
    case brushVertex = "brush_vertex"
    case brushFragment = "brush_fragment"
    case sessionCommitVertex = "session_commit_vertex"
    case sessionFragment = "session_fragment"
    case waterColorInit = "water_color_init"
    case waterColorMix = "water_color_mix"
    case layerVertex = "layer_vertex"
    case layerFragment = "layer_fragment"
}
