name: Bismush
targets:
  # MARK: - Application
  Bismush:
    type: application
    platform: macOS
    scheme:
      testTargets:
        - Bismush_UnitTests
    dependencies:
      - target: BismushKit_macOS
      - target: BismushUI_macOS
    entitlements:
      path: Sources/Bismush/Supports Files/Bismush.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
    info:
      path: Sources/Bismush/Supports Files/Info.plist
      properties:
        CFBundleDocumentTypes:
          - CFBundleTypeIconFiles: []
            CFBundleTypeName: Bismush Canvas File
            LSItemContentTypes:
                - jp.mzp.bismush.canvas
        UTExportedTypeDeclarations:
          - UTTypeConformsTo:
              - com.apple.package
            UTTypeDescription: Bismush Canvas File
            UTTypeIcons: []
            UTTypeIdentifier: jp.mzp.bismush.canvas
            UTTypeTagSpecification:
              public.filename-extension: ["bismush"]
    preBuildScripts:
      - path: Scripts/swiftformat.sh
        name: Swift Format
    postCompileScripts:
      - script: Scripts/swiftlint.sh
        name: Swiftlint
    sources:
      - Sources/Bismush

  MobileBismush:
    type: application
    platform: iOS
    dependencies:
      - target: BismushKit_iOS
      - target: BismushUI_iOS
    scheme:
      testTargets:
        - MobileBismush_UnitTests
    info:
      path: Sources/MobileBismush/Supports Files/Info.plist
      properties:
        CFBundleDocumentTypes:
          - CFBundleTypeIconFiles: []
            CFBundleTypeName: Bismush Canvas File
            LSItemContentTypes:
                - jp.mzp.bismush.canvas
        UTExportedTypeDeclarations:
          - UTTypeConformsTo:
              - com.apple.package
            UTTypeDescription: Bismush Canvas File
            UTTypeIcons: []
            UTTypeIdentifier: jp.mzp.bismush.canvas
            UTTypeTagSpecification:
              public.filename-extension: ["bismush"]

    entitlements:
      path: Sources/MobileBismush/Supports Files/MobileBismush.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
    settings:
      SUPPORTS_MACCATALYST: true
    preBuildScripts:
      - path: Scripts/swiftformat.sh
        name: Swift Format
    postCompileScripts:
      - script: Scripts/swiftlint.sh
        name: Swiftlint
    sources:
      - Sources/MobileBismush

  # MARK: - Framework
  BismushKit:
    type: framework
    platform: [macOS, iOS]
    scheme:
      testTargets:
        - BismushKit_UnitTests_${platform}
    info:
      path: Frameworks/BismushKit/Supports Files/Info.plist
    preBuildScripts:
      - path: Scripts/swiftformat.sh
        name: Swift Format
      - path: Scripts/clang-format.sh
        name: clang-format
    postCompileScripts:
      - script: Scripts/swiftlint.sh
        name: Swiftlint
    sources: 
      - Frameworks/BismushKit
    settings:
      MTL_LANGUAGE_REVISION: Metal24

  BismushUI:
    type: framework
    platform: [macOS, iOS]
    scheme:
      testTargets:
        - BismushUI_UnitTests_${platform}
    dependencies:
      - target: BismushKit_${platform}
    info:
      path: Frameworks/BismushUI/Supports Files/Info.plist
    preBuildScripts:
      - path: Scripts/swiftformat.sh
        name: Swift Format
      - path: Scripts/clang-format.sh
        name: clang-format
    postCompileScripts:
      - script: Scripts/swiftlint.sh
        name: Swiftlint
    sources:
      - Frameworks/BismushUI

  # MARK: - Tests
  Bismush_UnitTests:
    type: bundle.unit-test
    platform: macOS
    dependencies:
      - target: Bismush
    info:
      path: Tests/UnitTests/Bismush/Info.plist
    sources:
      - Tests/UnitTests/Bismush
    settings:
      GENERATE_INFOPLIST_FILE: true

  MobileBismush_UnitTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MobileBismush
    sources:
      - Tests/UnitTests/MobileBismush
    settings:
      GENERATE_INFOPLIST_FILE: true

  BismushKit_UnitTests:
    type: bundle.unit-test
    platform: [macOS, iOS]
    sources:
      - Tests/UnitTests/BismushKit
    info:
      path: Tests/UnitTests/BismushKit/Info.plist
    dependencies:
      - target: BismushKit_${platform}
    settings:
      GENERATE_INFOPLIST_FILE: true

  BismushUI_UnitTests:
    type: bundle.unit-test
    platform: [macOS, iOS]
    sources:
      - Tests/UnitTests/BismushUI
    info:
      path: Tests/UnitTests/BismushUI/Info.plist
    dependencies:
      - target: BismushUI_${platform}
    settings:
      GENERATE_INFOPLIST_FILE: true

# MARK: - Aggregate scheme
schemes:
  CI.macOS:
    build:
      targets:
        Bismush: all
    test:
      targets:
        - Bismush_UnitTests
        - BismushKit_UnitTests_macOS
        - BismushUI_UnitTests_macOS
  CI.iOS:
    build:
      targets:
        MobileBismush: all
      config: CI
    test:
        targets:
            - BismushKit_UnitTests_iOS
            - BismushUI_UnitTests_iOS
            - MobileBismush_UnitTests
        config: CI

  All.macOS:
    build:
      targets:
        Bismush: all
    test:
      testPlans:
        - path: All.xctestplan
          defaultPlan: true
  All.iOS:
    build:
      targets:
        MobileBismush: all
    test:
      testPlans:
#        - path: Tests/Plans/All.iOS.xctestplan
#          defaultPlan: true
  All.Everything:
    build:
      targets:
        Bismush: all
        MobileBismush: all
      test:
        testPlans:
#          - path: Tests/Plans/All.Everything.xctestplan
#            defaultPlan: true
          - path: Tests/Plans/All-macOS.xctestplan
#          - path: Tests/Plans/All.iOS.xctestplan

configs:
  CI: debug
  Debug: debug
  Release: release
settings:
  base:
    DEVELOPMENT_TEAM: VG2YYSKSHY
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "-"
  configs:
    CI:
      DEVELOPMENT_TEAM:
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_IDENTITY: "-"

options:
  bundleIdPrefix: jp.mzp.bismus

  createIntermediateGroups: true

  deploymentTarget:
    iOS: "15o.0"
    macOS: "12.0"

  groupOrdering: 
    - order: [Sources, Frameworks, Tests, Scripts]

fileGroups:
  - README.md
  - project.yml
  - Scripts
  - BuildTools/.swiftlint.yml
  - BuildTools/Package.swift
  - .swiftformat
  - .github
  - .clang-format
  - Tests/Plans
