// DO NOT EDIT. This file is generated by Scripts/shader-names.rb.
enum FunctionName: String {
    case layerVertex = "layer_vertex"
    case layerFragment = "layer_fragment"
    case bezierInterpolation = "bezier_interpolation"
    case waterColorInit = "water_color_init"
    case waterColorMix = "water_color_mix"
    case brushVertex = "brush_vertex"
    case brushFragment = "brush_fragment"
}
