#!/usr/bin/ruby

function_names = []

Dir.glob('**/*.metal') do |file|
  File.readlines(file).each do |line|
    if line =~ /^(?:kernel|vertex|fragment)\s+\w+\s+(\w+)/
      function_names << $1
    end
  end
end

puts <<END
// DO NOT EDIT. This file is generated by #{__FILE__}. 
enum FunctionName: String {
END

for function_name in function_names do
  head, *tail = function_name.split('_')
  const_name = head + tail.map(&:capitalize).join('')
  puts %Q/  case #{const_name} = "#{function_name}" /
end

puts '}'
